openapi: 3.0.0
info:
  title: 'API CraftCorner'
  description: "Cette APi permet d'accéder à toutes les fonctionnalités de l'application CraftCorner."
  contact:
    email: maxime.polese@le-campus-numerique.fr
  version: 1.0.0
paths:
  /shops:
    post:
      tags:
        - Shops
      summary: 'Create a new shop'
      operationId: bf1ecbd2dd07c06d915c0a5480a6c4d3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - shop_name
                - shop_theme
                - biography
              properties:
                shop_name:
                  type: string
                  example: 'My Shop'
                shop_theme:
                  type: string
                  example: Dark
                biography:
                  type: string
                  example: 'This is my shop'
              type: object
      responses:
        201:
          description: 'Shop created successfully'
        401:
          description: Unauthenticated
        422:
          description: 'Invalid data'
      security:
        -
          sanctum: []
  /users:
    get:
      tags:
        - Users
      summary: 'Get a list of users'
      operationId: 7e2f5799553ec93c9c43e2a58490d447
      responses:
        200:
          description: 'Successful operation'
        400:
          description: 'Invalid request'
