services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-laravel
    ports:
      - 8000:80
    networks:
      - craftcorner-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DB: craftcornerdata
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ../mysql-data:/var/lib/mysql
    networks:
      - craftcorner-network
    environment:
      MYSQL_DATABASE: craftcornerdata
      MYSQL_ROOT_PASSWORD: test
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -ptest || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  craftcorner-network:
